

BOT_NAME = "imdb250"

SPIDER_MODULES = ["imdb250.spiders"]
NEWSPIDER_MODULE = "imdb250.spiders"

ROBOTSTXT_OBEY = True

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"

MONGO_SERVER = 'localhost'
MONGODB_PORT = 27017
MONGODV_DB = 'SCRAPING.JSON'
MONGODB_COLLECTION = 'movies' 